#!/usr/bin/env python
from config import Config
from pathlib import Path

userdir = str(Path.home())
config = Path(userdir, '.SolarisInstaller')

if __name__ == "__main__":
    cfg = Config(config)
    cfg.show_pretty()
